config/routes.rb
UiBase::Engine.routes.draw do
  get 'info' => 'info#index', as: :info
  get 'info/send_test_email_to_current_user', as: :test_email
  get 'info/reset_all_views', as: :reset_all_views
  get 'error' => 'error#index', as: :error
  get 'availability/check' => 'info#check_availability'
end

app/controllers/ui_base/application_controller.rb
module UiBase
  class ApplicationController < ActionController::Base

    protect_from_forgery with: :reset_session, prepend: true

    layout 'layouts/application'

    helper UiBase::LayoutHelper
    helper Rails.application.helpers

    before_action :init_search_params
    before_action :store_and_set_search_params, :store_and_set_per_page, only: [:index, :search]
    before_action :store_back_url

    def set_locale
      begin
        locale = params[:locale] || session[:locale]
        I18n.locale = locale || I18n.default_locale
        begin
          session[:locale] = I18n.locale
        rescue
          Rails.logger.warn "Set locale to session failed!"
        end
      rescue I18n::InvalidLocale
        I18n.locale = I18n.default_locale
      end
    end

    def store_back_url
      return if controller_name == 'sessions'
      return unless request.format == :html
      return unless ['index', 'show'].include? action_name
      session[:back_url] = request.original_url.split('?').first rescue :back
    end

    def back_url
      if session[:back_url] == request.original_url.split('?').first
        :back
      else
        session[:back_url]
      end
    end

    def init_search_params
      params[:q] ||= {}
    end

    def reset_session_search_params
      (session[:q][controller_name]['index'] = nil) rescue nil
      (session[:q][controller_name]['search'] = nil) rescue nil
      redirect_to action: 'index'
    end

    def search
      index
      render :index
    end

    def store_and_set_search_params
      # Equalize /search and /index and /
      action = action_name == 'search' ? 'index' : action_name
      # Store
      unless params[:q].empty?
        # Oracle kennt leider keine case insensitives LIKE -.-
        if ActiveRecord::Base.configurations[Rails.env]['adapter'] =~ /oracle/
          params[:q].each do |key, value|
            # this enables case insensitive search with _cont suffix
            # this fix requires lowercase on the database content also
            # see extension on RansackObject in lib
            if key.to_s.match(/_cont/)
              params[:q][key] = value.downcase
            end
          end
        end
        session[:q] = (session[:q] || {}).deep_merge({controller_name => { action => params[:q] }})
      end
      # Load
      @search_params = session[:q][controller_name][action] rescue {}
      @search_params_present = @search_params.present? && @search_params_present.nil?
    end

    def set_search_param_default(name, value)
      if @search_params_present == false
        name = name.to_sym
        params[:q][name] = value if params[:q][name].nil?
        store_and_set_search_params
      end
    end

    def store_and_set_per_page
      session[:per_page] = {} if session[:per_page].blank?
      # Store
      if params[:per_page]
        session[:per_page] = session[:per_page].deep_merge({controller_name => { action_name => params[:per_page].to_i }})
        # Falls plötzlich 50 Einträge pro Seite angezeigt werden, befindet sicher der Anwender ggf.
        # auf einer hohen Seitenzahl, die keine Einträge mehr hat! Lösung:
        redirect_to page: 1
        return
      end
      # Load
      @per_page = session[:per_page][controller_name][action_name].to_i rescue 10
      @per_page = 10 if @per_page > 100 || @per_page < 1
    end

  end
end

app/controllers/ui_base/error_controller.rb
module UiBase
  class ErrorController < UiBase::ApplicationController

    skip_before_action :store_and_set_search_params, :store_and_set_per_page, :store_back_url

    def index
    end
    
  end
end

app/controllers/ui_base/info_controller.rb
module UiBase
  class InfoController < UiBase::ApplicationController

    skip_before_action :store_and_set_search_params, :store_and_set_per_page, :store_back_url, :init_search_params, only: [:check_availability]

    def index
    end

    def check_availability
      render plain: 'Alive and kicking!'
    end

    def send_test_email_to_current_user
      email = current_user.email
      begin
        TestMailer.test_email(email).deliver!
      rescue *SMTP_ERRORS, Errno::ECONNREFUSED => error
        redirect_to info_path, alert: (I18n.t('info.send_email_failed') + "<br/><br/>#{error.message}").html_safe
        return
      end
      redirect_to info_path, notice: I18n.t('info.email_test_success')
    end

    def reset_all_views
      session[:q] = {}
      redirect_to info_path, notice: I18n.t('info.reset_all_views_success')
    end

  end
end

app/helpers/ui_base/application_helper.rb
module UiBase
  module ApplicationHelper

    def user_is_admin?
      current_user.user_type == 'admin'
    end

    def tel_to(text)
      groups = text.to_s.scan(/(?:^\+)?\d+/)
      link_to text, 'tel:' + groups.join('-')
    end

    def button_link_to(*args, &block)
      options = args.extract_options!

      button_type = options.delete :type
      button_size = options.delete :size
      button_icon = options.delete :icon
      button_icon_position = options.delete :icon_position
      css = "btn btn-default #{options[:class]}"
      css << " btn-#{button_type.to_s.dasherize}" if button_type.present?
      css << " btn-#{button_size}" if button_size.present?
      options[:class] = css.strip

      if block_given?
        route = args.first
        label = capture(&block)
      else
        label = args.first
        route = args.second
      end

      if button_icon.present?
        icon_tag = content_tag(:i, nil, class: "fa fa-fw fa-#{button_icon.to_s.dasherize}")
        if button_icon_position == :right
          label = h(label) + ' ' + icon_tag
        else
          label = icon_tag + ' ' + h(label)
        end
      end
      if options[:disabled]
        capture_haml do
          haml_tag 'span', class: options[:class] + ' disabled' do
            concat label
          end
        end
      else
        link_to(label.html_safe, route, options) + ' '
      end
    end
  end
end

app/helpers/ui_base/flash_helper.rb
# Original gem was lacking Rails 5 support:
# https://github.com/scottvrosenthal/twitter-bootswatch-rails-helpers/blob/master/app/helpers/twitter/bootswatch/flash_helper.rb
module UiBase
  module FlashHelper

    def bootswatch_flash(alert_dismissable=true)
      alert_dismissable_class = alert_dismissable ? ' alert-dismissable' : ''
      flash_messages = ''
      flash.each do |type, message|
        next if type == "timedout" # workaround for devise
        alert_type_class = bootswatch_alert_types(type)
        if alert_dismissable
        alert_div = content_tag(:div, raw('<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>') + message, :class => "alert #{alert_type_class}#{alert_dismissable_class}")
        else
          alert_div = content_tag(:div, raw(message), :class => "alert #{alert_type_class}")
        end
        flash_messages << alert_div if message
      end
      raw(flash_messages)
    end

    def bootswatch_flash_block(alert_dismissable=true)
      output = ''
      flash.each do |type, message|
        output << bootswatch_flash_container(type, alert_dismissable) do
            message
        end
      end
      raw(output)
    end

    def bootswatch_flash_container(type, alert_dismissable=true, &message)
      alert_dismissable_class = alert_dismissable ? ' alert-dismissable' : ''
      alert_type_class = bootswatch_alert_types(type)
      message_html = capture(&message)
      if alert_dismissable
        output = content_tag(:div, :class => "alert #{alert_type_class}#{alert_dismissable_class}") do
          '<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>'.html_safe.safe_concat(message_html)
        end
      else
        output = content_tag(:div, :class => "alert #{alert_type_class}") do
          message_html.html_safe
        end
      end
      raw(output)
    end

    def bootswatch_alert_types(alert_type)
      #Rails 4.1 started using Strings instead of Symbol.
      case alert_type
        when :info, 'info' then 'alert-info'
        when :notice, :success, 'notice', 'success' then 'alert-success'
        when :alert, :error, 'alert', 'error' then 'alert-danger'
        else 'alert-warning' # warning
      end
    end

  end
end

app/helpers/ui_base/info_helper.rb
module UiBase
  module InfoHelper


    def used_engines
      specs = Bundler.environment.specs.to_hash
      gems = {}
      specs.each do | k,v |
        gems[k] = v.first.version.version if ['ui_base','job_management','simple_form_extended','ui_base', 'perfect_history'].include?(k) || k =~ /authentication/
      end
      gems
    end

    def hostname
      if !ENV["HOSTNAME"]
        if !ENV["COMPUTERNAME"]
          return `hostname`
        end
        return ENV["COMPUTERNAME"]
      end
      ENV["HOSTNAME"]
    end

    def nls_lang
      return ENV["NLS_LANG"] if ENV["NLS_LANG"]
      nil
    end

  end
end

app/helpers/ui_base/layout_helper.rb
module UiBase
  module LayoutHelper

    def title(title)
      @title = title
    end

    def page_header(a_string)
      @page_header = a_string
    end

  end
end

app/views/ui_base/info/index.html.haml
- if user_signed_in?
  - title t(:runtime_information)

  .row
    - version_file = "#{Rails.root}/log/versions.log"
    - version_file = "#{Rails.root}/VERSION" unless File.exist?(version_file)
    - if File.exist?(version_file)
      .col-xs-12
        .panel.panel-default
          .panel-heading Version Info
          .panel-body
            - File.readlines(version_file).each do |line|
              = line
              %br

    .col-xs-12
      %table.table.table-striped.table-vcenter.table-nowrap
        %thead
          %tr
            %th= t('info.name')
            %th= t('info.value')
        %tbody
          %tr
            %td= t('info.application_name')
            %td= "#{Settings.application_name || '-'} (#{Settings.application_short_name || '-'})"
          %tr
            %td= t('info.ruby_version')
            %td= "#{RUBY_VERSION}p#{RUBY_PATCHLEVEL} (#{RUBY_PLATFORM})"
          %tr
            %td= t('info.rubygems_version')
            %td= Gem::RubyGemsVersion
          - if ENV['GIT_REVISION']
            %tr
              %td= t('info.git_revision')
              %td= ENV['GIT_REVISION']
          - if ENV['GIT_BRANCH']
            %tr
              %td= t('info.git_branch')
              %td= ENV['GIT_BRANCH']
          - if ENV['VERSION']
            %tr
              %td= t('info.version')
              %td= ENV['VERSION']
          %tr
            %td= t('info.rails_version')
            %td= Rails::VERSION::STRING
          %tr
            %td= t('info.application_root')
            %td= File.expand_path(Rails.root.to_s)

          %tr
            %td= t('info.application_server_name')
            %td= hostname

          %tr
            %td= t('info.rails_env')
            %td= Rails.env

          %tr
            - used_engines.each do | name,version |
              %tr
                %td= name
                %td= version

          %tr
            %td= t('info.database')
            %td.truncate.truncate-100= "#{ActiveRecord::Base.configurations[Rails.env]['database']} (#{ActiveRecord::Base.configurations[Rails.env]['adapter']})"
          %tr
            %td= t('info.database_schema_version')
            %td= ActiveRecord::Migrator.current_version rescue nil
          %tr
            %td= t('info.nls_lang')
            %td= nls_lang || '-'
          - if Settings.bpv_wsdl
            %tr
              %td= t('info.authentication_service')
              %td= Settings.bpv_wsdl
          - if Settings.ldap_host
            %tr
              %td= t('info.ldap_host')
              %td= Settings.ldap_host
          %tr
            %td= t('info.logged_in_from')
            %td.truncate.truncate-100= request.ip
          %tr
            %td= t('info.bootstrap_size')
            %td
              %span.visible-xs XS
              %span.visible-sm SM
              %span.visible-md MD
              %span.visible-lg LG
          %tr
            %td= t('info.reset_all_views')
            %td= link_to t('info.reset_all_views_now'), reset_all_views_path
          %tr
            %td= t('info.send_test_email_to_current_user')
            %td
              - email = controller.current_user.email
              - if email.present?
                = link_to t('info.send_to_email_address', email_address: email), test_email_path
              - else
                = t('info.user_has_no_email_address')